name: GCP dev/stag Terraform Provisioning

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - stag
      region:
        description: "Select region"
        required: true
        type: choice
        options:
          - uscentral1

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ inputs.env }}
      REGION: ${{ inputs.region }}
      PROVIDER: gcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Set working directory with formatted region
        id: working_dir
        run: |
          FORMATTED_REGION=$(echo "${{ env.REGION }}" | sed 's/-/_/g')
          echo "working_dir=gcp/envs/${{ env.ENV }}/ww_$FORMATTED_REGION" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terraform Init
        run: make init

      - name: Terraform Apply
        run: make apply
